Blog/urls.py
from django.urls import path
from Blog.views import blog, categorie
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
		path('blog/', blog, name="blog"),
		path('blog/categorie/<int:categorie_id>/', categorie, name="categorie"), 
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) #CON ESTO LE DIGO A DJANGO DONDE DEBE CONSULTAR LOS ARCHIVOS DE MEDIA A TRAVEZ DE LA URL UBICADA EN  SETTINGS

Cart/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="cart"

urlpatterns = [
		path("add/<int:Item_id>/", views.AddingItem, name="add"),
		path("remove/<int:Item_id>/", views.RemovingItem, name="remove"),
		path("clear/", views.ClearCart, name="clear"),

]

Orders/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name="Orders"

urlpatterns = [
		path('order/', views.orders, name="order"),
]
 

ProyectoFullWeb/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
		path('',  include("FullWeb.urls")),
		path('',  include("Services.urls")),
		path('',  include("Blog.urls")),
		path('',  include("Contact.urls")),
		path('',  include("Shop.urls")),
		path('', include("Cart.urls")),
		path('', include("authentication.urls")),
		path('', include("Orders.urls")),

]

Shop/urls.py
from django.urls import path
from Shop.views import Shop
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
		path('shop/', Shop, name="shop"),
]

Cart/models.py
from django.db import models

Shop/models.py
from pyexpat import model
from tkinter import CASCADE
from turtle import title
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
	name=models.CharField(max_length=30,null=True)
	created=models.DateField(auto_now_add=True)
	uploaded=models.DateField(auto_now_add=True)
	class Meta:
		verbose_name='category'
		verbose_name_plural='categories'
	def __str__(self):
		return self.name

class Item (models.Model):
	name=models.CharField(max_length=30,null=True)
	description=models.CharField(max_length=50)
	price=models.FloatField()
	image=models.ImageField(upload_to='blog',null=True, blank=True)
	owner=models.ForeignKey(User, on_delete=models.CASCADE)
	categories=models.ManyToManyField(Category)
	created=models.DateField(auto_now_add=True)
	uploaded=models.DateField(auto_now_add=True)
	class Meta:
		verbose_name='item'
		verbose_name_plural='items'
	def __str__(self):
		return self.name

Cart/views.py
from re import I
from django.shortcuts import redirect
from .cart import Cart
from Shop.models import Item
# Create your views here.

def AddingItem(request, Item_id):
	cart=Cart(request)
	item=Item.objects.get(id=Item_id)
	cart.addItem(Item=item)
	return redirect("shop")

def RemovingItem(request, Item_id):
	cart=Cart(request)
	item=Item.objects.get(id=Item_id)
	cart.subtractItem(Item=item)
	return redirect("shop")

def ClearCart(request):
	cart=Cart(request)
	cart.cleanCart()
	return redirect("shop")

Shop/views.py
from django.shortcuts import render
from .models import Item, Category
# Create your views here.

def Shop(request):
	Shoplist=Item.objects.all()
	return render(request, 'Shop/',{'items': Shoplist})

def categorie(request, categorie_id):
	categorieid=Category.objects.get(id=categorie_id)
	categorielist=Item.objects.filter(categories=categorieid)
	return render(request, 'Blog/categorie',{'categorie': categorieid,'posts': categorielist})

Shop/templates/cart/widget.html
<table class="table table-borderless"
	style="background-color:rgba(24, 64, 8);color: white;border-radius: 10%; margin-top: auto;">
	<thead>
		<tr>
			<th colspan="3" class="text-center">
				Shopping Cart
			</th>
		</tr>
		<tr class="text-center">
			<th>Name</th>
			<th>Unid.</th>
			<th>Precio</th>
		</tr>
	</thead>
	<tbody>
		{% if request.session.cart.items %}
		{% for key, value in request.session.cart.items %}
		<tr class="text-center">
			<td>{{value.name}}</td>
			<td>{{value.unit}}&nbsp;&nbsp;<a href="{% url 'cart:add' value.Item_id %}" class="btn btn-sm btn-success">+</a>
				<a href="{% url 'cart:remove' value.Item_id %}" class="btn btn-sm btn-success">-</a>
			</td>
			<td>{{value.price}}</td>
		</tr>
		{% endfor %}
		{% else %}
		<tr>
			<td colspan="3">
				<div class="alert alert-danger text-center">
					No products in my cart
				</div>
			</td>
		</tr>
		{% endif %}
	</tbody>
	<tfoot>
		<tr>
			<td colspan="2">
				My Cart Total: $ {{total_import_cart}}
			</td>
			<td>
				<a href="{% url 'cart:clear' %}" class="btn btn-success">Clear</a>
				{% if request.session.cart.items %}
				<a href="{% url 'Orders:order' %}" class="btn btn-success">CheckOut</a>
				{% endif %}
			</td>
		</tr>
	</tfoot>
</table>